version: '3.8'

services:
  flask-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=mongouser_name
      - MONGODB_PASSWORD=mongouser_password
    ports:
      - "8082:8082"
    networks:
      - app-network

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BASE_URL=http://localhost:8082
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - flask-app
      - react-app

networks:
  app-network:
    driver: bridge
